[package]
name = "rustalot"
version = "0.1.0"
authors = ["Keane O'Kelley <me@keane.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
regex = "1"
lazy_static = "1.4.0"